#suhasdevops:)
#
---
- name: Create AWS Instance
  hosts: localhost
  tasks:
    - ec2:
        key_name: mykey
        instance_type: t2.micro
        image: ami-09d9776c
        region: us-east-1
        wait: yes
        count: 1
        vpc_subnet_id: subnet-3cfzsde12
        assign_public_ip: yes
        instance_tags:
          Name: webserver
        aws_access_key: ####################
        aws_secret_key: ########################################
