##suhasdevops :)
#
---
- name: Ansible gather EC2 informaion
  hosts: localhost
  tasks:
    - ec2_instance_facts:
        region: "us-east-1"
        filters:
          "tag:Name": test
        aws_access_key: ###############
        aws_secret_key: ####################################
      register: ec2_metadata

#    - debug: msg="{{ ec2_metadata.instances }}"
    - debug:
        msg:
          - "public_ip: {{ ec2_metadata.instances[0].public_ip_address }}"
          - "instance_id: {{ ec2_metadata.instances[0].instance_id }}"
          - "instance_type: {{ ec2_metadata.instances[0].instance_type }}"
          - "launch_time: {{ ec2_metadata.instances[0].launch_time }}"
          - "key_name: {{ ec2_metadata.instances[0].key_name }}"

    - name: Sending an e-mail using Gmail SMTP servers
      mail:
        host: "smtp.gmail.com"
        port: 465
        username: "username@gmail.com"
        password: "app_password"
        secure: starttls
        to: "James <bond007@gmail.com>"
        subject: "Ansible-report"
        body:
          "This email is generated by Ansible while execution ec2_info.yml.\n\n
          public_ip: {{ ec2_metadata.instances[0].public_ip_address }}\n
          instance_id: {{ ec2_metadata.instances[0].instance_id }}\n
          instance_type: {{ ec2_metadata.instances[0].instance_type }}\n
          launch_time: {{ ec2_metadata.instances[0].launch_time }}\n
          key_name: {{ ec2_metadata.instances[0].key_name }}"

## Note:
# Required app_password for gamil account access use link:
# https://www.lifewire.com/get-a-password-to-access-gmail-by-pop-imap-2-1171882
