#suhasdevops:)
#
---
- name: Stop AWS instances
  hosts: localhost
  gather_facts: false
  vars:
    instance_ids:
      - 'i-04f6676a4a'
     # - 'i-xxxxxx'
     # - 'i-xxxxxx'
    region: us-east-1
  tasks:
    - name: Stopping the AWS instance
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: stopped
        wait: True
        vpc_subnet_id: subnet-3cefge12
        assign_public_ip: yes
        aws_access_key: ####################
        aws_secret_key: ########################################
        
