---
- name: Ansible gather EC2 informaion
  hosts: localhost
  tasks:
    - ec2_instance_facts:
        region: "us-east-1"
        filters:
          "tag:Name": test
        aws_access_key: #################
        aws_secret_key: #############################
      register: ec2_metadata

#    - debug: msg="{{ ec2_metadata.instances }}"
    - debug:
        msg:
          - "public_ip:{{ ec2_metadata.instances[0].public_ip_address }}"
          - "instance_id:{{ ec2_metadata.instances[0].instance_id }}"
          - "instance_type:{{ ec2_metadata.instances[0].instance_type }}"
          - "launch_time:{{ ec2_metadata.instances[0].launch_time }}"
          - "key_name:{{ ec2_metadata.instances[0].key_name }}"
