#suhasdevops:)
#
---
- name: Start stopped AWS instances
  hosts: localhost
  tasks:
    - local_action:
        module: ec2
        instance_tags:
          Name: webserver
        state: running
        region: us-east-1
        aws_access_key: ####################
        aws_secret_key: ########################################
        
